
#define  debugC

#if defined ( debugC )
__CONFIG( FCMEN_OFF & IESO_OFF & CLKOUTEN_OFF & BOREN_ON & CPD_OFF & CP_OFF & MCLRE_ON & PWRTE_OFF & WDTE_SWDTEN & FOSC_HS );
__CONFIG( LVP_OFF & BORV_HI & STVREN_OFF & PLLEN_OFF & VCAPEN_OFF & WRT_OFF);
#else	//Program
__CONFIG( FCMEN_OFF & IESO_OFF & CLKOUTEN_OFF & BOREN_ON & CPD_ON & CP_ON & MCLRE_ON & PWRTE_ON & WDTE_SWDTEN & FOSC_HS );
__CONFIG( LVP_ON & BORV_HI & STVREN_OFF & PLLEN_OFF & VCAPEN_OFF & WRT_OFF);
#endif





